name: itshouldbesimpler
favicon: null
layout_spectrum: 0.8714609250891954
typography_spectrum: 0.4490357022732496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.47132771275937557
  lightness: 0.4363626919221133
  saturation: 0.6571209481917322
  rhythmicContrast: 0.6708812850993127
purpose: []
